spring:
  application:
    name: lovable-clone
    description: A clone of the lovable application

  datasource:
    url: jdbc:postgresql://localhost:5432/testDB
    username: postgres
    password: anee_admin
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

jwt:
  secret-key: 7d2fc59bfce6fad848fd8e9d42cbbd5b1e0812640dd0cdfc4faa32ca8fe97b65

stripe:
  api:
    secret: sk_test_51TB8lJKXMuyFBUTMM8hx7l6cbXDnyajjCUPjvVi5KsAubRiwYOQcIXMKfrGXUjufdwhhFyS7O7GbRRoe7NINX2DZ00pcjUu2xL
  webhook:
    secret: whsec_9d4c48782aeb9031b2555b155d89734a065237c90b02a60d86981abe55dc862b

client:
    url: http://localhost:8080