spring:
  application:
    name: lovable-clone
    description: A clone of the lovable application

  datasource:
    url: jdbc:postgresql://localhost:5432/testDB
    username: postgres
    password: anee_admin
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

jwt:
  secret-key: 7d2fc59bfce6fad848fd8e9d42cbbd5b1e0812640dd0cdfc4faa32ca8fe97b65